name: Advent2015
version: '0.1.0.0'
author: Marc Zuo
maintainer: zealotzuo@gmail.com
license: UnspecifiedLicense
extra-source-files:
- README.md
dependencies:
- base >=4.13 && <4.14
- safe >=0.3 && <0.4
- parsec >=3.1 && <3.2
- split >=0.2 && <0.3
- bytestring >=0.10 && <0.20
- matrix >=0.3 && <0.4
- pureMD5 >=2.1 && <2.2
- array >=0.5 && <0.6
- either-unwrap >=1.1 && <1.2
- containers >=0.6 && <0.7
- lens >=4.13 && <4.23
- extra >=1.7 && <1.8
- text >=1.2 && <1.3
- vector >=0.11 && <0.20
- unordered-containers >=0.2 && <0.3
- aeson >=1.4 && <1.5
executables:
  advent2015:
    main: Main.hs
    source-dirs: src
